In [2]:
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)

In [ ]:
# example code from curriculum
# n_trials = nrows = 10_000
# n_dice = ncols = 3

# rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
# rolls



In [8]:
# 1. How likely is it that you roll doubles when rolling two dice?

#problem set up, need 10000 trials (large # trials), rolling 2 dice
#each roll of 2 dice will be a row

ntrials = nrows = 10000
ndice = ncols = 2

rolls = np.random.choice([1,2,3,4,5,6], ntrials * ndice).reshape(nrows, ncols)
print(rolls)


[[3 2]
 [3 3]
 [6 5]
 ...
 [3 6]
 [5 3]
 [2 6]]


In [ ]:
# example code from curriculum
# n_simulations = nrows = 10**5
# n_dice_rolled = ncols = 3

# rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)

# (pd.DataFrame(rolls)
#  .apply(lambda row: 3 in row.values, axis=1)
#  .mean())

In [11]:
#now that we have sample rolls, determine which rolls are doubles
#need data in dataframe instead of matrix?
rolls = pd.DataFrame(rolls)
#then apply lambda function to look for doubles?
doubles = rolls.apply(lambda row: row[0]==row[1], axis=1)
#then find the average of the times the row is true
doubles.mean()

# exobrain answer verification https://www.stayorswitch.com/blog/with-two-dice-whats-the-probability-of-rolling-doubles/

0.1636

In [17]:
# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads?

# exobrain https://www.google.com/search?client=safari&rls=en&q=If+you+flip+8+coins,+what+is+the+probability+of+getting+exactly+3+heads&ie=UTF-8&oe=UTF-8

#problem set up, 1 row per trial, 8 columns, 1=heads, 0=tails
#example from lesson
# sums_by_trial = rolls.sum(axis=1)
# sums_by_trial

ntrials = nrows = 10000
ncoins = ncols = 8

flips = np.random.choice([1, 0], nrows * ncols).reshape(nrows, ncols)
#now add the row total
sumbytrial = flips.sum(axis=1)
# then get the average of those where the sum is 3
(sumbytrial==3).mean()

0.2181

In [ ]:
# 2a. What is the probability of getting more than 3 heads?

In [18]:
# get the average where the sum is greater than 3
(sumbytrial>3).mean()

0.636

In [4]:
# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two
# billboards I drive past both have data science students on them?

# example weighted probability from lesson
# Let's make an un-fair coin that flips heads .60
# probabilities = [.75, .25]
# flips = np.random.choice(["Heads", "Tails"], size=10_000, p=probabilities)
# (flips == "Heads").mean()

probabilities = [.75, .25]
billboard = np.random.choice(["Web", "Data"], size=10000, p=probabilities)
data = (billboard == "Data").mean()
# mean of this for "Data" is probability of 1 billboard being data science
# square that probability to find odds of both being data
data**2



0.06375625

In [50]:
# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
# If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to 
# buy some poptarts on Friday afternoon?

# 17 start Monday before class, the range of poptarts eaten per week is 7.5 to 22.5
# but can't eat .5 of a poptart so use 8 and 23 for hypothetical poptarts that would be eaten
# generate random whole numbers in this range to represent # of poptarts eaten each week
eaten_weekly = np.random.randint(low=8, high=23, size=10000)

left = 17 - eaten_weekly
(left>=1).mean()


0.6099

In [39]:
# 4. alternative calculation
# Corey and exobrain https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html
# use normal because have mean and standard dev, but want 10000 trials in sets of 5 days
eaten = np.random.normal(3, 1.5, size=(10000, 5))
# this gives a np array of values, need to remove negative amounts because can't eat negative poptarts
type(eaten)
# exobrain https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-90.php
eaten[eaten<0]=0
# convert to dataframe
eaten = pd.DataFrame(eaten)
# apply lambda function to sum each row for total eaten
weekly2 = eaten.apply(lambda row: row.sum(), axis=1)
# if weekly is less than or equal to 16 then there are poptarts left on Friday afternoon
(weekly2<=16).mean()


0.607

In [32]:
# 5. Compare Heights
# -Men have an average height of 178 cm and standard deviation of 8cm.
# -Women have a mean of 170, sd = 6cm.
# -If a man and woman are chosen at random, P(woman taller than man)?

# get a sample of 10000 men and 10000 women with heights within 1 standard dev of mean
men = np.random.normal(loc=178, scale=8, size=10000)
women = np.random.normal(loc=170, scale=6, size=10000)

# subtract men - women, if result is negative woman is taller
taller = men - women

# find average where taller is negative
(taller<0).mean()

0.2137

In [59]:
# 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted
# and the installation fails. What are the odds that after having 50 students download anaconda, no one has an
# installation issue? 

# 1/250 chance of fail convert to percent success and percent fail
probabilities = [.996, .004]
# generate 10,000 trails in sets of 50 students
install = np.random.choice(["Pass", "Fail"], size=(10000, 50), p=probabilities)
# find average where fail in the set of 50
# convert to df to apply lambda to look for Fail in set
install = pd.DataFrame(install)
# apply lambda function and average row where Fail present subtract % fail from 1 to get % all pass
all_pass = 1 - (install.apply(lambda row: "Fail" in row.values, axis=1).mean())
all_pass

0.8166

In [62]:
1*.996**50*.004**0

0.8184024506760997

In [60]:
# 6a. # 100 students?
probabilities = [.996, .004]
# generate 10,000 trails in sets of 100 students
install = np.random.choice(["Pass", "Fail"], size=(10000, 100), p=probabilities)
# find average where fail in the set of 50
# convert to df to apply lambda to look for Fail in set
install = pd.DataFrame(install)
# apply lambda function and average row where Fail present subtract % fail from 1 to get % all pass
all_pass = 1 - (install.apply(lambda row: "Fail" in row.values, axis=1).mean())
all_pass

0.6707000000000001

In [63]:
1*.996**100*.004**0

0.6697825712726458

In [65]:
# 6b. What is the probability that we observe an installation issue within the first 150 students that
# download anaconda?

probabilities = [.996, .004]
# generate 10,000 trails in sets of 100 students
install = np.random.choice(["Pass", "Fail"], size=(10000, 150), p=probabilities)
# find average where fail in the set of 50
# convert to df to apply lambda to look for Fail in set
install = pd.DataFrame(install)
# apply lambda function and average row where Fail present subtract % fail from 1 to get % all pass
any_fail = install.apply(lambda row: "Fail" in row.values, axis=1).mean()
any_fail

0.4505

In [64]:
# P of 1 issue in 1st 150 = 1 - P(no issues in 1st 150)
1-(1*.996**150*.004**0)

0.4518483022503271

In [68]:
# 6c. How likely is it that 450 students all download anaconda without an issue?
probabilities = [.996, .004]
# generate 10,000 trails in sets of 100 students
install = np.random.choice(["Pass", "Fail"], size=(10000, 450), p=probabilities)
# find average where fail in the set of 50
# convert to df to apply lambda to look for Fail in set
install = pd.DataFrame(install)
# apply lambda function and average row where Fail present subtract % fail from 1 to get % all pass
all_pass = 1 - (install.apply(lambda row: "Fail" in row.values, axis=1).mean())
all_pass

0.16169999999999995

In [66]:
1*.996**450*.004**0

0.1647032961586129

In [ ]:
# exbrain binomial example
# A real world example. A company drills 9 wild-cat oil exploration wells, each with an estimated probability of
# success of 0.1. All nine wells fail. What is the probability of that happening?

# Let’s do 20,000 trials of the model, and count the number that generate zero positive results.

#sum(np.random.binomial(9, 0.1, 20000)==0)/20000
# # answer = 0.38885, or 38%.

In [78]:
# 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?

unlikely = sum(np.random.binomial(3, 0.7, 20000)==0)/20000
print(unlikely)

# How likely is it that a food truck will show up sometime this week?
likely = 1-(sum(np.random.binomial(7, 0.7, 20000)==0)/20000)
print(likely)

0.02495
0.99965


In [87]:
# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

# 23 people, probability of any particular day of birth = 1/365
# generate a random day from 1 to 365 for each of 23 people
birthdays = np.random.randint(1, 365, size=(100, 23))
print(birthdays)


# stop here ran out of time before walkthrough, need to goggle how to find duplicate values in pandas df row?

birthdays = pd.DataFrame(birthdays)
occurances = birhtdays.apply(lambda row: "Fail" in row.values, axis=1)
occurances = np.unique(birthdays, return_counts = True)
print(occurances)

[[297  62 323 ... 133 102 207]
 [119  18 235 ... 211 333 314]
 [130 122 145 ...  61  64  22]
 ...
 [ 25   5 344 ... 231 167 205]
 [284  90 227 ... 106 158 302]
 [ 91 298 172 ... 304 308 135]]
(array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146

In [83]:
# exobrain https://betterexplained.com/articles/understanding-the-birthday-paradox/

# 23 people = 253 pairs ((23*22)/2)
# odds that bdays are different = 364/365
# odds that any pair has same bday
1-(364/365)**253

0.5004771540365807

In [72]:
# 8a. # What if it's 20 people? 



In [71]:
pairs = (20*19)/2
1-(364/365)**pairs

0.4062294594924657

In [70]:
# 8b. 40?



In [69]:
pairs = (40*39)/2
1-(364/365)**pairs

0.8823356309842172